DropDown/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DropDown.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public IEnumerable<Clinic> Clinics { get; set; }

    }
}

DropDown/Models/City.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DropDown.Models
{
    public class City
    {
        public int id { get; set; }
        public string name { get; set; }

        public int state_id { get; set; }

        public State state { get; set; }
        public IEnumerable<Clinic> Clinics { get; set; }


    }
}

DropDown/Models/Clinic.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DropDown.Models
{
    public class Clinic
    {
        public int Id { get; set; }
        public string Name { get; set; }
        
        public City City { get; set; }

        public Category Category { get; set; }


    }
}

DropDown/Models/Country.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DropDown.Models
{
    public class Country
    {
        public int id { get; set; }
        public string sortname { get; set; }
        public string name { get; set; }

  

    }
}

DropDown/Models/DropDownDbContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace DropDown.Models
{
    public class DropDownDbContext:DbContext
    {
        public DbSet<Country> Countries { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<Clinic> Clinics { get; set; }
        public DbSet<Category> Categories { get; set; }
    }
}

DropDown/Models/State.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Security.AccessControl;
using System.Web;

namespace DropDown.Models
{
    public class State
    {
        [Key]
        public int state_id { get; set; }
        public string name { get; set; }

        [ForeignKey("Country")]
        public int country_id { get; set; }
        public Country Country { get; set; }

        public IEnumerable<City> Cities { get; set; }
  
    }
}

DropDown/Models/UserProfile.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.UI.WebControls;

namespace DropDown.Models
{
    public class UserProfile
    {
        [Key]
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string UserImage { get; set; }

        public int? CountryId { get; set; }
    }
}

DropDown/Models/VMClass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DropDown.Models
{
    public class VMClass
    {
        public List<Country> Countries { get; set; }
        public List<Category> Categories { get; set; }

    }
}

DropDown/Controllers/DropDownCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DropDown.Models;

namespace DropDown.Controllers
{
    public class DropDownCController : Controller
    {
        DropDownDbContext db = new DropDownDbContext();
        // GET: DropDownC
        public ActionResult Index()
        {
            ViewBag.StateName = db.States.Where(c=>c.country_id==64).ToList();
            ViewBag.CategoryName = db.Categories.ToList();
            return View();
        }

       

        public JsonResult GetCityByID(int ID)
        {
            return Json(db.Cities.Where(c => c.state_id == ID), JsonRequestBehavior.AllowGet);
        }

        #region MyRegion
        /* public ActionResult AllUser()
     {
         return View(db.UserProfiles.ToList());
     }*/

        /*  public ActionResult AllClinic()
          { 

              return View(db.Clinics.ToList());
          }*/

        #endregion
        [HttpPost]
        public ActionResult GetClinic(int stateId=-1, int cityId =-1, int categoryid=-1)
        {

            //return $" - City  : {cityId} co- State : {stateId}  -Categoery : {categoryid}";
            return View("AllClinic",db.Clinics.Where(c => c.Category.Id == categoryid && c.City.id == cityId).ToList());

        }
    }
}

DropDown/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DropDown.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DropDown/Views/DropDownC/AllClinic.cshtml
@model IEnumerable<DropDown.Models.Clinic>

@{
    ViewBag.Title = "AllClinic";
}

<h2>AllClinic</h2>



@foreach (var item in Model) {
    <div class="form-control">
        @Html.DisplayNameFor(model => model.Name)
        @Html.DisplayFor(modelItem => item.Name)
    </div>
}

DropDown/Views/DropDownC/AllUser.cshtml
@model IEnumerable<DropDown.Models.UserProfile>

@using GridMvc.Html


    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
<link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/gridmvc.min.js")" type="text/javascript"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<link href="@Url.Content("~/Content/Css/bootstrap.min.css")" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "AllUser";
}

<h2>AllUser</h2>


<h2>First commit in git hub</h2>

@Html.Grid(Model).Columns(columns =>
{
    columns.Add(foo => foo.UserName).Titled("User Name").SetWidth(110).Filterable(true);
    columns.Add(foo => foo.Email).Sortable(true);
    columns.Add(foo => foo.Tel).Sortable(true);
    columns.Add(foo => foo.Address).Sortable(true);
}).WithPaging(4)

DropDown/Views/DropDownC/Index.cshtml
@using DropDown.Models
@model DropDown.Models.Country
@{
    ViewBag.Title = "Index";
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
}
<script>
    $(function () {
       

        $("#St").change(function () {
            $.get("/DropDownC/GetCityByID",
                { ID: $("#St").val() },
                function (data) {
                    //$("#city").empty();
                    $.each(data,
                        function (index, row) {
                            $("#city").append(`<option value="${row.id}">${row.name}</option>`);
                        });
                });
        });
    });
</script>

<h2>Index</h2>
@using (Html.BeginForm("GetClinic","DropDownC",FormMethod.Post))
{

    <select class="form-control" id="St" name="stateId">
    <option value="-1">Choose Country </option>
    @foreach (var count in (List<State>)ViewBag.StateName)
    {
        
        <option value="@count.state_id">@count.name</option>

    }
</select>


    <select id="city" class="form-control" name="cityId">
        <option value="-1">Choose area</option>
    </select>

    <select class="form-control"  id="CaID" name="categoryid"> 
        <option value="-1">Choose Category </option>
        @foreach (var count  in  (List<Category>) ViewBag.CategoryName)
        {
            <option value="@count.Id">@count.Name </option>

        }
    </select>

    <div class="form-group">
        <input type="submit" class="btn btn-success" value="Get Data"/>
    </div>
}

DropDown/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

DropDown/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DropDown/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

DropDown/Views/Shared/_AjaxGridPager.cshtml
@model Grid.Mvc.Ajax.GridExtensions.AjaxGridPager
@if (Model.Pages < 2)
{
    return;
}

<div class="grid-footer">
    <div class="grid-pager">
        <ul class="pagination">
            <li><a href="#" class="grid-prev-page" title="Previous Page" style="display: none"><span class="fa fa-backward"></span></a></li>
            @{if (Model.Pages > Model.PagePartitionSize + 2 &&
                  Model.PagePartitionSize > 0)
            {
                <li class="active"><a class="grid-page-link" data-page="1">1</a></li>
                <li><a href="#" class="grid-pageSetLink prev" style="display: none;" data-pageset='1' data-partitionsize="@Model.PagePartitionSize">...</a></li>
                for (int i = 1; i < Model.PagePartitionSize + 1; i++)
                {
                    var currentPage = i + 1;
                    <li><a href="#" class="grid-page-link" data-page='@currentPage'>@currentPage</a></li>
                }

                <li><a href="#" class="grid-pageSetLink next" data-pageset='2' data-partitionsize="@Model.PagePartitionSize">...</a></li>
                <li><a href="#" class="grid-page-link" data-page='@Model.Pages'>@Model.Pages</a></li>
            }
            else
            {
                <li class="active"><a class="grid-page-link" data-page="1">1</a></li>
                for (int i = 1; i < Model.Pages; i++)
                {
                    var currentPage = i + 1;
                    <li><a href="#" class="grid-page-link" data-page='@currentPage'>@currentPage</a></li>
                }
            }
            }
            <li><a href="#" title="Next Page" class="grid-next-page"><span class="fa fa-forward"></span></a></li>
        </ul>
    </div>
</div>

DropDown/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>